version: '3.8'

services:
  web: # Nombre del servicio, lo usaremos en el cron
    image: nginx:alpine
    container_name: spa-activities-web
    restart: unless-stopped
    ports:
      # Puerto 8080 del host (Pi) mapeado al 80 del contenedor
      - "9988:80"
    volumes:
      # Volumen del contenido web (como antes)
      - .:/usr/share/nginx/html:ro
      # Volumen para la configuración Nginx personalizada
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf:ro